apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "{{ .Values.portPrometheus }}"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.portPrometheus }}
      targetPort: {{ .Values.portPrometheus }}
      protocol: TCP
      name: prometheus
  selector:
    app: {{ .Values.name }}
